name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v2
      - name: install
        run: npm i
      - name: test
        run: npm test -- --ci --coverage
